# Generated by Django 3.0 on 2020-01-01 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('image', models.URLField(max_length=300)),
                ('alt', models.URLField(blank=True, max_length=300)),
                ('title', models.URLField(blank=True, max_length=300)),
                ('previous', models.CharField(max_length=300)),
                ('next', models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
