# Generated by Django 3.0 on 2020-01-01 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moa', '0002_comic_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comic',
            name='created',
        ),
        migrations.AddField(
            model_name='comic',
            name='date',
            field=models.CharField(default='a', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
