language: python
dist: xenial
python:
  - "3.8"
install:
  - pip install pipenv
  - pipenv install --dev
script:
  - pipenv run test
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/pipenv